import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./_components/header";
import "./globals.css";
import SignOutButton from "./_components/SignOutButton";
import MyMsalProvider from "./_utils/msalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyMsalProvider>
          <main>
            <div className="w-full text-center">
              <h1 className="text-3xl font-bold text-gray-700 mb-2">You are logged in</h1>
              <div className="m-4">User Avatar</div>
              <SignOutButton />
            </div>
            {children}
          </main>
        </MyMsalProvider>
      </body>
    </html >
  );
}
